version: '3.3'
services:
  server:
    container_name: server
    build: ./server
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://username:password@mongo:27017
    depends_on:
      - mongo
    command: npm run prod
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongoData:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: username
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://username:password@mongo:27017/
      ME_CONFIG_BASICAUTH: false


